name: Bump version
run-name: Bump version

on:
  workflow_call:
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

jobs:
  bump-version:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2

      - name: Assume IAM Role
        id: assume-iam-role
        uses: bitterbridge/github-actions/assume-iam-role@v0.0.51
        with:
          role-to-assume: ${{ vars.IAM_ROLE_TO_ASSUME }}

      - name: Get GitHub Token
        id: get-github-token
        uses: bitterbridge/github-actions/get-github-token@v0.0.51
        with:
          github-app-id-secret-path: ${{ vars.APP_ID_SECRET_PATH }}
          github-app-private-key-secret-path: ${{ vars.APP_PRIVATE_KEY_SECRET_PATH }}

      - name: Bump version
        id: bump-version
        uses: bitterbridge/github-actions/bump-version@v0.0.51
        with:
          github-token: ${{ steps.get-github-token.outputs.github-token}}
